// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: 'admin' | 'user'
          status: 'pending' | 'approved' | 'rejected' | 'suspended'
          has_limits: boolean
          max_books: number | null
          max_pages_per_month: number | null
          max_chat_messages_per_month: number | null
          current_books_count: number
          pages_processed_this_month: number
          chat_messages_this_month: number
          month_reset_date: string
          created_at: string
          updated_at: string
          approved_at: string | null
          approved_by: string | null
        }
        Insert: Omit<Database['public']['Tables']['user_profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>
      }
      books: {
        Row: {
          id: string
          original_filename: string
          file_type: 'pdf' | 'epub'
          file_size: number
          file_hash: string
          file_path: string
          title: string | null
          author: string | null
          extracted_text: string | null
          text_hash: string | null
          status: 'uploaded' | 'processing' | 'ready' | 'error'
          processing_error: string | null
          total_pages: number | null
          total_chunks: number | null
          processed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['books']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['books']['Insert']>
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
